version: '3.7'

services:
  # Service for MySQL
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: course_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Service for PHP with Nginx
  web:
    build:
      context: ./backend
    container_name: php-web
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  # Nginx service for reverse proxy
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  mysql_data:
