---
- name: Setup Database Server and phpMyAdmin
  hosts: dbserver
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    mysql_root_password: "your_root_password"
  tasks:
    - name: Install MySQL Python libraries
      apt:
        name: 
          - python3-pymysql
        state: present

    - name: Install MariaDB server
      apt:
        name: mariadb-server
        state: present

    - name: Start and enable MariaDB service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Install phpMyAdmin
      apt:
        name: phpmyadmin
        state: present

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted

    - name: Create MySQL user for phpMyAdmin
      mysql_user:
        login_user: "root"
        login_password: "{{ mysql_root_password }}"
        name: "phpmyadminuser"
        password: "1234"
        host: "localhost"
        state: present
        priv: "*.*:ALL"

    - name: Create a database for phpMyAdmin user
      mysql_db:
        login_user: "root"
        login_password: "{{ mysql_root_password }}"
        name: "phpmyadmin_db"
        state: present

    - name: Grant all privileges to phpMyAdmin user
      mysql_user:
        login_user: "root"
        login_password: "{{ mysql_root_password }}"
        name: "phpmyadminuser"
        host: "localhost"
        priv: "phpmyadmin_db.*:ALL"
        state: present
